### ISSUE TITLE
Where is the pre-built version? There is no bin directory

### ISSUE THREAD

**Issue by hakunin** [orlandohill/waxeye#29]
Hi,
I am trying to use waxeye and both readme and the docs talk about pre-built waxeye, but neither sourceforce, or the downloads here have a `bin` folder inside the archive.

It would be awesome if there was a tap for homebrew btw.

**Comment by adabru** [comment]
For me, the download is available at sourceforge: https://sourceforge.net/projects/waxeye/

**Comment by hakunin** [comment]
Does it have a `bin` folder the documentation refers to?

**Comment by adabru** [comment]
Yes

**Comment by hakunin** [comment]
This is what I see, no bin folder anywhere.
https://www.dropbox.com/s/21aa5ii6t3pzmeh/Screenshot%202017-03-22%2015.26.35.png?dl=0

**Comment by orlandohill** [comment]
Hi Michal,

On SourceForge there are pre-built versions for Unix and Windows. You
mention homebrew, so I assume you're on MacOS and downloaded the -src
package.

**Comment by hakunin** [comment]
Thanks, I downloaded it from the website which points directly to the source.
