### ISSUE TITLE
UTF-8, char classes, and JavaScript vs C

### ISSUE THREAD

**Issue by glebm** [orlandohill/waxeye#30]
Context: Our grammar has a token that is a union of several Unicode ranges (always UTF-8), and use the generated parser in C in JavaScript.

The waxeye grammar currently only allows specifying char ranges between two single bytes ([waxeye.waxeye](https://github.com/orlandohill/waxeye/blob/4537605762bcb5485304d115d6b3013c416e9652/grammars/waxeye.waxeye#L49-L55)).

The C parser is not Unicode-aware and operates on individual bytes. This may be the right choice as it allows waxeye to parse even binary streams.

This does mean we must define a UTF-8 specific grammar, for example:

```
# GreekVar is alpha (α) to omicron (ο)
GreekVar <- \<ce> [\<b1>-\<bf>]
```

However, the JavaScript parser operates on `String`, where each character is a Unicode codepoint, so the grammar above would not work in JavaScript.

To make such grammar work in JavaScript, we'd need to do byte-level parsing there as well.
The only performant way to achieve that in JavaScript is to use the [TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) API. The only issue with that API is not available on IE / Edge.

Ideally, the JavaScript parser should also optionally keep providing string positions and not just byte indices in the AST.

I'm considering changing the JavaScript parser to operate on bytes using TextEncoder. Thoughts / objections?

/cc @ddrone @jishi9

**Comment by adabru** [comment]
For my tasks I use custom parsers only to parse Unicode data.  Therefore I'd appreciate the possibility to use Unicode characters in the grammar file. 

If use case of ASCII parsing exists, I think a (maybe automatically from grammar file derived?) choice of using Unicode or ASCII will serve most use cases. 

Therefore I think adding ASCII parsing to the Javascript parser or adding Unicode parsing to the c parser won't compromise on use cases and won't break existing applications. Or adding both, if your use case requires it.

**Comment by orlandohill** [comment]
I found a couple of entries about Unicode in my old TODO list.

The intention was to extend the definition of 'Hex' in the grammar language to allow specifying all Unicode code points, not just 8 bit ones. So, for example, `\<00>` `\<0000>` `\<000000>` and `\<00000000>` for 8, 16, 24 and 32 bit codes.

Unicode support was going to be added to the C version. I have no idea which libraries can/should be used these days.

I would prefer that different encoding formats be supported at the API level, and that a grammar file just specify the language after any decoding.

The overall design philosophy was to make things as easy as possible for the grammar writer and the user of the parsing APIs, while keeping the feature set as small as possible.

For example, the goal would be to allow the following grammar, regardless of parser implementation language.

`GreekVar <- [α-ο]`

**Comment by glebm** [comment]
@orlandohill OK, I wrote a proposal here: #31. The proposal is focused on Unicode character classes because for our use case they are necessary.

**Comment by glebm** [comment]
Closing this and opening separate issues for the individual action items as discussed.
