### ISSUE TITLE
Should AST nodes have input position information?

### ISSUE THREAD

**Issue by orlandohill** [orlandohill/waxeye#36]
I never really used it. It was a speculative feature, so arguably shouldn't have been added to the API in the first place.

Is it useful enough to justify being there?

**Comment by glebm** [comment]
Yes, please! We really need it. It's useful for a number of things in industrial applications:

1. Error-reporting.
2. Syntax highlighting based directly on the grammar.
3. Implementing autocompletion in editors.

This was actually a must-have criteria for us when choosing a parser generator.

**Comment by orlandohill** [comment]
Thanks, that's great to know!

A text editor with syntax highlighting was my hypothetical use-case.
