### ISSUE TITLE
Support Unicode escapes in the grammar

### ISSUE THREAD

**Issue by glebm** [orlandohill/waxeye#49]
The syntax I like most is:

```
\uXXXXXX
```

Other alternatives are:

```
\u{XXXXXX}
```

And:

```
\x{XXXXXX}
```

In all cases, 1 to 6 hex digits are accepted.

~~Need to decide whether to support this in literals or only character classes.~~
Unicode escapes should be allowed in literals and character classes.

**Comment by orlandohill** [comment]
I'm fine with `\uXXXXXX`.

Is there a reason why you wouldn't want to allow Unicode escapes in literals? They're basically already in the grammar with `Hex`, I just never got to implementing Unicode support before development stopped.

**Comment by glebm** [comment]
No reason, they should be allowed, that settles it. I didn't realize they already allow `Hex`.

**Comment by glebm** [comment]
While implementing this, I've realized that there is no way to distinguish between

"**\uAAA**b" and "**\uAAAb**" (escape is in bold, the first `b` is an actual letter)

While this can be worked around by escaping the b as well, this is trouble for generated grammar files.
For this reason, decided on `\u{XXXXXX}`.

**Comment by orlandohill** [comment]
Good, makes sense.
