### ISSUE TITLE
JavaScript API: Representation of empty ASTs

### ISSUE THREAD

**Issue by orlandohill** [orlandohill/waxeye#70]
The representation of empty ASTs was changed in the JavaScript API when moving to the new parsing machine design. A `form` field was introduced to distinguish between a regular AST node and one that should be considered to contain no information except that parsing was successful. This adds redundant information to many AST nodes, because the user will only check for an empty AST at the top of the tree. An empty AST will never be a subtree.

1. Remove the `form` field from the `AST` class.
2. Revert to using boolean value `true` to represent a successful parse result that has no other information. This is also used in the current Python and Ruby APIs.
- OR
2. Subclass the base `AST` class with a `EmptyAST` class, similar to the Java API.

Advantage of the subclass approach is the ability to report where parsing ended from a voided starting non-terminal, in the case that it is valid to not consume all input. Disadvantage is less simplicity.

**Comment by glebm** [comment]
We could also use an empty `type` string to represent the empty AST, because the `type` is guaranteed to not be empty otherwise.

**Comment by orlandohill** [comment]
Yes, using an empty `type` string sounds good.
