### ISSUE TITLE
Ability to start parsing from any non-terminal

### ISSUE THREAD

**Issue by orlandohill** [orlandohill/waxeye#73]
I suspect that people will want to be able to start parsing from an arbitrary non-terminal. The `parse` method could be overloaded in the appropriate way for each language.

**Comment by glebm** [comment]
The appropriate way for JavaScript means that the starting non-terminal should be the last method.
It's fine for different runtimes to have slightly different APIs though, as the APIs should be idiomatic and idioms differ.

**Comment by orlandohill** [comment]
Yes, that makes complete sense.
