### ISSUE TITLE
JavaScript: Rewrite in TypeScript

### ISSUE THREAD

**Issue by glebm** [orlandohill/waxeye#77]
Easier to reason about with types, and easier to avoid mistakes / typos.

**Comment by darmie** [comment]
Great, I wanted to suggest this.

**Comment by glebm** [comment]
Almost done with the rewrite here https://github.com/glebm/waxeye/tree/typescript, just fixing a few remaining issues!

**Comment by orlandohill** [comment]
Great idea! I doubt I'd choose CoffeeScript, these days.
