### ISSUE TITLE
publish waxeye.js on npm

### ISSUE THREAD

**Issue by maxleiko** [orlandohill/waxeye#8]
Could you publish waxeye on npm registry ?

**Comment by maxleiko** [comment]
@orlandohill & @JoshuaGross

**Comment by maxleiko** [comment]
@orlandohill I will need your npm login, to transfer the ownership ;)

**Comment by orlandohill** [comment]
@maxleiko I've signed up on npm, username is orlandohill. https://www.npmjs.com/~orlandohill

**Comment by JoshuaGross** [comment]
Excellent, thanks you two! I appreciate the fast turn-around :)

**Comment by maxleiko** [comment]
@orlandohill [done](https://www.npmjs.com/package/waxeye/access)

**Comment by orlandohill** [comment]
@maxleiko Thanks!
